### ISSUE TITLE
Invalid JSON Encoder with Flask 0.10

### ISSUE THREAD

**Issue by psgibbs** [jzempel/flask-exceptional#11]
Current version uses flask.json.econder.encode_basestring, but 'encoder' no longer exists in the flask.json module, could potentially use flask.json._json.encoder, but that feels a little hacky.

**Comment by jzempel** [comment]
Thanks for opening this issue. I'm digging into it, but I think dereferencing `flask.json._json` is the way to go. It's the only handle that Flask is providing to the underlying module. It's probably fair to say that my safe encoding monkey-patch is hacky to begin with.
