### ISSUE TITLE
AttributeError: 'functools.partial' object has no attribute '__module__'

### ISSUE THREAD

**Issue by tusharbabbar** [jzempel/flask-exceptional#12]
I am trying to use Flask-Exceptional on Mac OSX version 10.9.3 on python 2.7.5 .
On calling `Exceptional(app)` an error is encountered.
Here's the traceback.

```
Traceback (most recent call last):
  File "__init__.py", line 1, in <module>
    from app import app, login_manager, redis_client, api
  File "/Users/tushar/dev/frankly/api/app.py", line 14, in <module>
    exceptional = Exceptional(app)
  File "/Library/Python/2.7/site-packages/flask_exceptional.py", line 53, in __init__
    self.init_app(app)
  File "/Library/Python/2.7/site-packages/flask_exceptional.py", line 100, in init_app
    app.handle_exception = self._get_exception_handler(app)
  File "/Library/Python/2.7/site-packages/flask_exceptional.py", line 198, in _get_exception_handler
    @wraps(handle_exception)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

Here's what i found on stackoverflow.
[Error encountered using decorator to update wrapper](http://stackoverflow.com/questions/11960007/error-encountered-using-decorator-to-update-wrapper)

Please Look into the problem.
Thanks.

**Comment by jzempel** [comment]
What version of Flask are you using?

**Comment by tusharbabbar** [comment]
I could solve the above error. It was due to conflict in `flask.ext.restful` and `flask.ext.exceptional`. 
I have configured the flask app with exceptional but I am unable to understand the flow to log error into my airbrake account.
On using `Exceptional.test()` I encounter an exception saying `Exception: Congratulations! Your application is configured for Exceptional error tracking.` but there is no Exception visible on the airbrake account.
Please help.
Thanks

**Comment by jzempel** [comment]
This extension is for [Exceptional](http://www.exceptional.io/), not Airbrake. Please see the docs: https://pythonhosted.org/Flask-Exceptional/ :smiley:

**Comment by tusharbabbar** [comment]
Thanks for the reply but it seems that exceptional is now converted to airbrake.
Check this - https://www.exceptional.io/signups/new.
Probably this is the reason why I cant see any logs on occurrence of errors from this flask-extention.

**Comment by jzempel** [comment]
Thanks for that - totally missed the memo (would've been nice if @exceptional gave the platform developers a heads-up). I'll do some digging and see what's up.
