### ISSUE TITLE
str.format incompatible with Python < 2.6

### ISSUE THREAD

**Issue by jab** [jzempel/flask-exceptional#5]
I'd like to use flask-exceptional in my Flask app, but I'm on App Engine which is unfortunately still Python 2.5. Any interest in using something like https://github.com/florentx/stringformat so flask-exceptional won't break on Python 2.5?

**Comment by jzempel** [comment]
Thanks for bringing this to my attention.  I'd rather not add a non-core
dependency.  Rather, I'll switch to using %-based substitutions and deliver
an update ASAP.

Jonathan.

**Comment by jab** [comment]
Thanks, Jonathan. One other option if you wanted to preserve new-style string formatting without adding a non-core dependency is to just include a stripped-down version of stringformat, which is the approach taken by e.g. Logbook (see
https://github.com/mitsuhiko/logbook/blob/master/logbook/_stringfmt.py).

**Comment by jzempel** [comment]
Might be overkill for the handful of strings I needed to change. The most recent push addresses this issue. Version 0.4.2 is also available on pypi.

**Comment by jab** [comment]
Awesome, thanks for the quick turnaround.

**Comment by jab** [comment]
Just wanted to report that I got flask-exceptional up and running on App Engine and it's working great so far.

**Comment by jzempel** [comment]
Awesome. Thanks!
