### ISSUE TITLE
expose Exceptional object in app.extensions

### ISSUE THREAD

**Issue by jab** [jzempel/flask-exceptional#7]
Would be nice to be able to access the Exceptional object via app.extensions. The flask-babel extension for instance does this:

```
ipdb> pp app.extensions
{'babel': <flaskext.babel.Babel object at 0x102a51b10>,
 'exceptional': {'name': 'flask-exceptional',
                 'protocol_version': 5,
                 'version': 'unknown'}}
```

Is this a standard practice, or is there some other place it's kicking around?

**Comment by jzempel** [comment]
Good point.  I didn't see any clear guidance on this when I did the
extension.  But if it's good enough for Armin, it's good enough for me.
 I'll change to:

```
def init_app(self, app):
    ...
    app.extensions["exceptional"] = self
```

when I pull your other optimized set request.

**Comment by jab** [comment]
Sounds good to me. Thanks Jonathan.

**Comment by jzempel** [comment]
Updated (version 0.4.3) on github and pypi.
