### ISSUE TITLE
TypeError: <cStringIO...> is not JSON serializable

### ISSUE THREAD

**Issue by jab** [jzempel/flask-exceptional#8]
Flask-exceptional is throwing the following error whenever it tries to post an exception:

```
Traceback (most recent call last):
  File "/base/python27_runtime/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 174, in Handle
    result = handler(self._environ, self._StartResponse)
  File "packages/flask/app.py", line 1518, in __call__
    return self.wsgi_app(environ, start_response)
  File "packages/flask/app.py", line 1506, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "packages/flaskext/exceptional.py", line 142, in ret_val
    self._post_data(context)
  File "packages/flaskext/exceptional.py", line 184, in _post_data
    "exception": self.__get_exception_data(traceback)
  File "/base/python27_runtime/python27_dist/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/base/python27_runtime/python27_dist/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/base/python27_runtime/python27_dist/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/base/python27_runtime/python27_dist/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <cStringIO.StringI object at 0x2981158> is not JSON serializable
```

I am using the new python27 App Engine runtime.

**Comment by jzempel** [comment]
Joshua,

Thanks for raising this issue. I'm trying to track down the problem, but I'm not exactly sure what it might be. I'm pretty sure that your particular exceptional data has data formats that choke the default JSON encoder. We can fix that, but I'd like to know what those formats might be (dates, decimals, etc?).

There are a few things that could help:
1. Can you successfully execute the Flask-Exceptional test cases? (via setup.py test)
2. Can you successfully test your configuration? (see the Flask-Exceptional [docs](http://packages.python.org/Flask-Exceptional/); run Exceptional.test() in your Flask shell)
3. Would you be willing to accept a temporary, hacked exceptional.py that outputs a "print" of the dict that is failing the json.dumps() call?

**Comment by jab** [comment]
Hey Jonathan,

Thanks for the quick reply. Flask-Exceptional successfully posted the test exception to getexceptional.com when I ran Exceptional.test(..) from my Flask shell.

I added a call to log the result of `self.__get_exception_data(traceback)` in exceptional.py before trying to json serialize it, redeployed my app, and then triggered a 405. This resulted in two log messages:
http://paste.pocoo.org/show/498031/
http://paste.pocoo.org/show/498033/

Let me know if there's anything else I can do to help.

Thanks,
Josh

**Comment by jzempel** [comment]
That's a good start. But my guess is that the offending format is not inside the exception data. Could you setup a similar log call, except output the entire dict from line #180 before attempting the call to json.dumps()? Something like this:

```
temp = {
    "application_environment": self.__get_application_data(context.app),
    "client": client_data,
    "request": self.__get_request_data(context.app, context.request, context.session),
    "exception": self.__get_exception_data(traceback)
}
# Log temp here.
error_data = json.dumps(temp)
```

Thanks,
Jonathan.

**Comment by jab** [comment]
Ah, indeed, there is a single cStringIO.StringI object in error_data: the value of the 'os.wsgi.input' key. Is that sufficient, or would it help to see the entire object?

**Comment by jzempel** [comment]
That's fine - no need for the entire object. For now, you should be able to move forward with Flask-Exceptional by filtering that particular key in your configuration (see docs for details):

```
EXCEPTIONAL_ENVIRONMENT_FILTER = ['os.wsgi.input']
```

I'm going to give a little bit of thought to this. But my first instinct is not to embellish the JSON encoding and simply wrap all environment variables in a printable str(). In your case, that means the exceptional output will show `OS.WSGI.INPUT  <cStringIO.StringI object at 0x2981158>` rather than the actual value of the StringIO object.

Thoughts?

I'll let you know when I've posted a new version of Flask-Exceptional with a fix for this issue.

**Comment by jab** [comment]
Added `EXCEPTIONAL_ENVIRONMENT_FILTER = ('os.wsgi.input', 'os.wsgi.errors', 'os.werkzeug.request')` and now I've got things working again. Thanks for the workaround!

Calling `str` on the environ vars sounds right to me. Thanks.

**Comment by jzempel** [comment]
Josh,

The new 0.4.6 version with the fix for your issue is available on PyPI now. You should be able to use that without the filter workaround.

Cheers,
Jonathan.

**Comment by jab** [comment]
Confirmed the new version fixes the issue. Thanks Jonathan!
